# pubspec.yaml
name: tiri
description: "A Flutter-based mobile application for community help requests and resource sharing."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  defer_pointer: ^0.0.2
  flutter_launcher_icons: ^0.14.3
  dotted_border: ^3.1.0
  uuid: ^4.5.1
  google_maps_flutter: ^2.12.3
  country_picker: ^2.0.20
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.4
  retry: ^3.1.2
  web_socket_channel: ^2.4.0
  app_links: ^6.3.1
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
    - family: LexendDeca
      fonts:
        - asset: fonts/lexend_deca/static/LexendDeca-Regular.ttf
        - asset: fonts/lexend_deca/static/LexendDeca-Bold.ttf