name: kind_clock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.4.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  defer_pointer: ^0.0.2
  flutter_launcher_icons: ^0.14.3
  dotted_border: ^3.1.0
  uuid: ^4.5.1
  google_maps_flutter: ^2.12.3
  country_picker: ^2.0.20
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.4
  retry: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
    - family: LexendDeca
      fonts:
        - asset: fonts/lexend_deca/static/LexendDeca-Regular.ttf
        - asset: fonts/lexend_deca/static/LexendDeca-Bold.ttf