// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example configuration - you need to replace these with your actual Firebase project details.
/// Run `flutterfire configure` to automatically generate this file with your project settings.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key-here',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-project-id-here',
    authDomain: 'your-project-id-here.firebaseapp.com',
    storageBucket: 'your-project-id-here.appspot.com',
    measurementId: 'G-ABCDEF1234',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbIGrhg9FLL9LW07nf_tPK724X4RV7BQ',
    appId: '1:869913529630:android:7637a39112a998546c4d0f',
    messagingSenderId: '869913529630',
    projectId: 'tiri-ca1ca',
    storageBucket: 'tiri-ca1ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4aWXcs2_9C-WjU9KvdnaKz8JfFo1hndI',
    appId: '1:869913529630:ios:d5365a978e86c5996c4d0f',
    messagingSenderId: '869913529630',
    projectId: 'tiri-ca1ca',
    storageBucket: 'tiri-ca1ca.firebasestorage.app',
    iosBundleId: 'com.example.tiri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4aWXcs2_9C-WjU9KvdnaKz8JfFo1hndI',
    appId: '1:869913529630:ios:d5365a978e86c5996c4d0f',
    messagingSenderId: '869913529630',
    projectId: 'tiri-ca1ca',
    storageBucket: 'tiri-ca1ca.firebasestorage.app',
    iosBundleId: 'com.example.tiri',
  );
}