// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB31IBCmDFkFFimEI9taINcGKQl8W5scM',
    appId: '1:139235085545:web:a14584124780d4789af478',
    messagingSenderId: '139235085545',
    projectId: 'kind-clock-e28b8',
    authDomain: 'kind-clock-e28b8.firebaseapp.com',
    storageBucket: 'kind-clock-e28b8.firebasestorage.app',
    measurementId: 'G-VXFFQE8ZKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCJFJ4Rm7VuU0y8ZaBZLkXXD2z0Tz5NU',
    appId: '1:139235085545:android:93b4caea7552e9e59af478',
    messagingSenderId: '139235085545',
    projectId: 'kind-clock-e28b8',
    storageBucket: 'kind-clock-e28b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVKMPbt9av2er02GF_6kSwuqxLQkuTK4',
    appId: '1:139235085545:ios:2471c5240780f2f29af478',
    messagingSenderId: '139235085545',
    projectId: 'kind-clock-e28b8',
    storageBucket: 'kind-clock-e28b8.firebasestorage.app',
    iosBundleId: 'com.example.kindClock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVKMPbt9av2er02GF_6kSwuqxLQkuTK4',
    appId: '1:139235085545:ios:2471c5240780f2f29af478',
    messagingSenderId: '139235085545',
    projectId: 'kind-clock-e28b8',
    storageBucket: 'kind-clock-e28b8.firebasestorage.app',
    iosBundleId: 'com.example.kindClock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB31IBCmDFkFFimEI9taINcGKQl8W5scM',
    appId: '1:139235085545:web:e945696c9acf919e9af478',
    messagingSenderId: '139235085545',
    projectId: 'kind-clock-e28b8',
    authDomain: 'kind-clock-e28b8.firebaseapp.com',
    storageBucket: 'kind-clock-e28b8.firebasestorage.app',
    measurementId: 'G-LYWEBQWTY4',
  );
}
